//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasesBase.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"C:\\Users\\admin\\Documents\\Visual Studio" +
            " 2010\\Projects\\LPOO2_GRUPO_08\\pasteleria.mdf\";Integrated Security=True;Connect T" +
            "imeout=30;User Instance=True")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"D:\\FACULTAD\\TERCER AÑO\\2do CUATRIMESTR" +
            "E\\LABORATORIO DE PROGRAMACION ORIENTADO A OBJETOS II\\PROYECTOS\\TP FINAL2\\LPOO2_G" +
            "RUPO_08\\pasteleria.mdf\";Integrated Security=True;Connect Timeout=30;User Instanc" +
            "e=True")]
>>>>>>> 49b9500212d35c64c9e72c358df41ba7553bb1d4
        public string MyConnection {
            get {
                return ((string)(this["MyConnection"]));
            }
        }
    }
}
